#!/bin/sh
set R /
set FEXTRAS /fs/microsd/etc/extras.txt
ver all
dataman start
sh /etc/init.d/rc.board_sensors
# MAVLink on USB CDC ACM is now managed by rc.board_sensors
# (production mode only, to avoid console conflict in development mode)
if [ -f $FEXTRAS ]
then
    sh $FEXTRAS
fi
echo "Nucleo-H743ZI-FC startup complete"
